name: cenapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Permisos
  permission_handler: ^12.0.0+1
  
  # Compartir archivos
  share_plus: ^11.0.0

  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  
  # Mapas
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  
  # Geolocalización
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Documentos
  pdf: ^3.11.3
  excel: ^4.0.6
  flutter_pdfview: ^1.3.1
  open_file: ^3.3.2
  
  # Archivos y rutas
  path_provider: ^2.1.5
  path: ^1.8.3
  file_picker: ^10.1.2
  
  # Imágenes
  image_picker: ^1.0.4
  image: ^4.1.3  # Para manipulación y procesamiento de imágenes
  #image_gallery_saver: ^2.0.3
  
  # Utilidades
  intl: ^0.20.2
  uuid: ^4.5.1
  http: ^1.3.0
  syncfusion_flutter_xlsio: ^29.1.38
  syncfusion_officechart: ^29.1.38
  flutter_native_splash: ^2.4.4
  
  
  # Para información del dispositivo (necesario para detectar versión de Android)
  #device_info_plus: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter_native_splash:
  color: "#ffffff"
  image: assets/logoCenapp.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logoCenapp.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logoCenapp.png
    - assets/ciudades_colonia.json  
    - assets/openSans.ttf
    - assets/logotec.png